use_frameworks!

platform :ios, '13.0'

target 'IQKeyboardNotification_Example' do
  pod 'IQKeyboardNotification', :path => '../'

  target 'IQKeyboardNotification_Tests' do
    inherit! :search_paths

    
  end
end
